import { LevelMapConfig } from '../config/LevelConfig';
import { ArrowDirection, EArrowColor } from '../type/arrow';

export const Level1: LevelMapConfig = {
    levelId: 1,
    levelName: 'Level 1',
    mapWidth: 750,
    mapHeight: 1334,
    path: {
        pathPoints: [
            [-4, -4],
            [-4, -3],
            [-4, -2],
            [-4, -1],
            [-4, 0],
            [-4, 1],
            [-4, 2],
            [-4, 3],
            [-4, 4],
            [-3, 4],
            [-2, 4],
            [-1, 4],
            [0, 4],
            [1, 4],
            [2, 4],
            [3, 4],
            [4, 4],
            [4, 3],
            [4, 2],
            [4, 1],
            [4, 0],
            [4, -1],
            [4, -2],
            [4, -3],
            [4, -4],
            [3, -4],
            [2, -4],
            [1, -4],
            [0, -4],
            [-1, -4],
            [-2, -4],
            [-3, -4],
        ],
    },
    arrows: [
        {
            id: 1,
            startPos: [0, 0],
            offsetCoords: [
                [1, 0],
                [2, 0],
                [2, 1],
                [2, 2],
            ],
            direction: ArrowDirection.LEFT,
            colorType: EArrowColor.ORANGE,
        },
        {
            id: 2,
            startPos: [0, -3],
            offsetCoords: [
                [0, -2],
            ],
            direction: ArrowDirection.DOWN,
            colorType: EArrowColor.BLUE,
        },
    ],
    holes: [
        {
            id: 1,
            positions: [[0, 5.5], [0, 7]],
            colorTypes: [EArrowColor.BLUE, EArrowColor.ORANGE],
        },
    ],
};
